apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: f0l4b2syu-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: f0l4b2syu-nodejs 
  name: f0l4b2syu-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: f0l4b2syu-nodejs 
